### ISSUE TITLE
site changed to goone.pro and I can't fix it? 

### ISSUE THREAD

**Issue by devvratmiglani** [niveK77pur/gogoanime#11]
I tried setting xpath to the updated one but it didn't worked for me, thanks I seriously want it.

**Comment by devvratmiglani** [comment]
Seems like captcha is triggered, I say just add like it open browser and wants us to solve captcha, after then it can process other links using the cookies, I'm kind of noob with selenium

**Comment by niveK77pur** [comment]
Hello, and thank you for the issue! As you may or may not have noticed, I have not updated this repository in a very long while. Reason being &mdash; as you encountered yourself as well &mdash; the CAPTCHA! I had opened a related issue #10 about it myself before abandoning this project, simply to not let it die without justification.

# What happened?

The issue was that gogoanime was constantly changing their CAPTCHA in a very palpable attempt to block scrapers (such as this one). While trying to work around their new verification methods was definitely a very fun exercise and taught me a lot about web scraping, their latest version (at the time I abandoned the project) was impossible to solve with a simple script (even the inclusion of selenium could not help anymore).

They were the real deal where you had to *select pictures containing X* and so forth, which would probably have required including AI into this solution to automate the process. In issue #10 I found a semi-workaround, which is basically what you are proposing here, but I do not know if it still works as of today. After having bashed my head on this latest development in CAPTCHA, I decided that it was beyond my capabilities, and that gogoanime was not scrapeable anymore.

Also in response to your suggestion, having a window pop up and asking the user to solve the captcha would definitely be a viable fix, but I personally did not like the idea, because it would effectively take away from a fully automated download solution.

# In conclusion

I am terribly sorry for having indirectly wasted your time and energy on this, by not having indicated that I had abandoned the project (either with a message in the readme, or by archiving the project). That said, please allow me to give you some pointers and not leave you hanging here like that! My assumption is that you were looking for an anime downloader, and like me, gogoanime was probably your go-to site for watching them already.

## ani-cli

I moved to a different downloader which so far has been working excellent! The project appears very much alive, and whenever downloads stop working (because sites introduce new bot defense mechanisms for example) the devs so far have done their best to address the problems! The project in question is [ani-cli][anicli], please check it out! I remember having tried out a few alternatives to my own solution, and this one by far worked the best (at least by the time I abandoned this project here). Also to be clear, besides using the tool, I am not affiliated with it in any way shape or form.

## subsplease.org torrent

Ever since abandoning this project, I discovered the wonderful world of RSS feeds. As I enjoy watching seasonal anime, I became annoyed by the fact that the downloaders would require me to manually check for and download new episodes. So I was looking if there aren't any sites that provide RSS feeds for recently released episodes and I stumbled upon https://subsplease.org/

I have written another small Python script which reads their RSS feed, and downloads new episodes of your choice AUTOMATICALLY (the RSS feed has the torrent download links directly included, so no more scraping either)! You only run the script, and it will take care of everything for you; no more hunting the episodes! I have kept the script to myself, but seing that someone actually stumbled upon my work here, I will be happy to upload to GitHub my new RSS torrent downloader! Please let me know if you are interested!

Be aware however that it is a torrenting website/platform; so be sure to first check whether or not you'll get in trouble for torrenting in your country (generally speaking, not just anime specifically). ~~Also, there appear to be ways to circumvent legislative issues, but I will leave the research up to you if interested.~~

## livechart.me

https://www.livechart.me is an incredibly sweet site which basically shows you when new episodes release. The site itself does not provide any functionality to watch episodes, but that was perfectly fine for me; I simply wanted to see when new episodes are coming out!

If I remember correctly, this site also provides an RSS feed with recently released episodes. I thought it could be interesting to either merge this into my subsplease downloader, or to have it trigger another tool such as ani-cli to attempt a download when new episodes released. The idea would be that it works similar to my torrent downloader, but using ani-cli (which does not use torrenting; I personally fall back to ani-cli for seasonals if certain animes are not on subsplease.org).

I have not created anything in this direction however, it was just an idea I had floating around while I was putting together my subsplease solution. I thought I should share it for the sake of completeness.

---

With all that said, I will archive this project very soon, and update the README accordingly. If you are interested in my subplease.org downloader which automatically checks for and downloads new episodes for you, let me know and I will create a new project &mdash; in a way, I consider it a spiritual successor to this project here. Otherwise, [ani-cli][anicli] is where I have migrated towards myself, and I can highly recommend it for downloading episodes; it is simple in its capabilities (at least those I use), which is exactly what I was looking for.

[anicli]: https://github.com/pystardust/ani-cli

**Comment by devvratmiglani** [comment]
Ahh I'm glad bro you replied, I'm currently thinking of getting my hands back on to selenium, what I'm thinking doing is using the cookies back, I will create an event that will open up a browser tab for one time just to solve the captcha, then it doesn't matter what captcha it is, then I can just download all the episodes in a batch, this is also convenient otherwise I would need to make about 250 + click and blocking ads just to download about 50 episodes, your repo is just the starting of my hope.

I just hope that I could do that and I hope I would never let this repo die, foe now I can live in hope and thanks alot..

**Comment by devvratmiglani** [comment]
Yeah, I'm going to try out ani-cli

**Comment by devvratmiglani** [comment]
Actually you know, when I used your tool it's not like I want to download, I just like to use it. And so I'm fond with it.

**Comment by niveK77pur** [comment]
I absolutely see your point, manually downloading 50 episodes on a website is horrible! That was what initially motivated me to make this script! The ani-cli tool can do this as well however, it uses a different site to gogoanime though, but the quality of the videos is still excellent! If you need a working solution, I can highly recommend that one!

If you want something to simply play around with, then you have actually landed on an interesting repository! What initially started as an automation script for downloading anime, had slowly turned into a playground, a testing field, and a learning experience for web scraping, which eventually also had me introduce selenium!

I have tried to keep the code straight forward for this exact reason, and deliberately tried not abstract it too much and end up with a hard to read code base. I can only encourage you to fork the repository, and make it your own playground! Or simply play around with a local copy of the repository!

I am merely going to archive it because I have no plans to give this any more attention, and want to save poor souls like you the headache of stumbling over an abandoned project. I am not thinking of deleting it, so it will remain at your disposal :grin:

**Comment by devvratmiglani** [comment]
It actually gave me knowledge that we still can bypass captcha so I it take it as knowledge for me, 😂

Well I have hope due to this repo btw I'm pursuing a bachelor's degree in AI&ML so maybe one day I go beyond captcha using selenium and Ai 😁

**Comment by niveK77pur** [comment]
Awesome! I did a bachelor's in computer science, so I had a fair share of exposure to AI as well, plus I remember seeing plenty of tutorials online to solve captcha using AI. Technically it is totally doable! At the end of the day, I'd still say the simplest solution is to avoid or circumvent captcha entirely (for example by finding different sites to scrape)! ~~I say this with a slight grudge towards AI, I personally never enjoyed working with it (like the actual coding part), but I can't deny it allows us to do very cool stuff~~

I wish you the best of luck with your studies, and can't wait to see an AI powered anime downloader :wink:

**Comment by devvratmiglani** [comment]
Well Im just using Ani-cli in bash, and I get to know why you were encouraging me to use it. Damn it's a giant in features💀🔥🔥

Also best of luck to you for your prosperous career✨

**Comment by niveK77pur** [comment]
Indeed it is, and I probably only use a very small portion of what it can do lol

Thank you very much for the kind exchange! I shall close this issue, and put the repository to rest very soon!
